name: Build source distribution

on:
  push:
    branches: [ main ]

  # Allow run this workflow manually
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel
          python setup.py sdist
      - uses: actions/upload-artifact@v3
        with:
          name: sdist
          path: dist
